# Generated by Django 2.2.5 on 2019-10-02 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('GLO', 'GLO'), ('AIRTEL', 'AIRTEL'), ('9MOBILE', '9MOBILE')], max_length=10)),
                ('value', models.CharField(choices=[('100', '100'), ('200', '200'), ('500', '500'), ('1000', '1000'), ('1500', '1500'), ('2000', '2000')], max_length=4)),
                ('pin', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$')])),
            ],
        ),
        migrations.CreateModel(
            name='SoldPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networksold', models.CharField(choices=[('MTN', 'MTN'), ('GLO', 'GLO'), ('AIRTEL', 'AIRTEL'), ('9MOBILE', '9MOBILE')], max_length=10)),
                ('valuesold', models.CharField(choices=[('100', '100'), ('200', '200'), ('500', '500'), ('1000', '1000'), ('1500', '1500'), ('2000', '2000')], max_length=4)),
                ('pinsold', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$')])),
                ('datesold', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
